apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
spec:
  storageClassName: csi-disk-retain
  volumeName: pvc-0e1a9673-f7be-4ad5-9fd5-bcf4f4fb727b
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
