apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: anubis
  app.kubernetes.io/instance: anubis
  helm.sh/chart: anubis-0.0.1

configMapGenerator:
  - name: anubis-policy
    files:
      - botPolicies.yaml=./config/botPolicies.yaml
    options:
      disableNameSuffixHash: true
