apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-mail-gateway
  labels:
    app: express-mail-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-mail-gateway
  template:
    metadata:
      labels:
        app: express-mail-gateway
    spec:
      serviceAccountName: cpn
      containers:
        - name: express-mail-gateway
          image: quay.io/opentelekomcloud/express-mail-gateway:0.0.1
          command:
            ["/bin/bash", "-c"]
          args:
            ['cp /secrets/emg-env /usr/src/app/.env; npm run start']
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - containerPort: 6000
