{{- range .Values.clusterIssuers }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
{{- if eq .type "acme" }}
  acme:
    email: {{ .email | quote }}
    server: {{ .server | quote }}
    privateKeySecretRef:
      name: {{ .privateKeySecretRef }}
    solvers:
      {{- toYaml .solvers | nindent 6 }}
{{- else if eq .type "selfSigned" }}
  selfSigned: {}
{{- else if eq .type "ca" }}
  ca:
    secretName: {{ .secretName }}
{{- end }}
---
{{- end }}
