---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-proxy
spec:
  template:
    spec:
      serviceAccountName: oauth-proxy
      containers:
        - name: oauth-proxy
          livenessProbe:
            $patch: delete
          readinessProbe:
            $patch: delete
