---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpcenter-int
namePrefix: docsportal-internal-

components:
- ../../../../base

patches:
- path: deployment.patch.yaml
- path: service.patch.yaml
- path: serviceaccount.patch.yaml
- path: secret.patch.yaml
- path: ingress.patch.yaml
