apiVersion: v2
name: grafana
description: A Helm chart for Grafana that includes pre-defined dashboards and datasources
version: 0.1.0
dependencies:
  - name: grafana
    version: "10.5.15"
    repository: "https://grafana.github.io/helm-charts"
