apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-webhook-translator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitea-webhook-translator
    creationPolicy: Owner
  data:
  - secretKey: github-webhook-secret
    remoteRef:
      key: secret/zuul/connections/github
      property: webhook_token
  - secretKey: gitea-webhook-secret
    remoteRef:
      key: secret/zuul/connections/gitea
      property: webhook_token
