apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-webhook-translator
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /webhook
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - zuul.eco-preprod.tsi-dev.otc-service.com
    secretName: zuul-tls
  rules:
  - host: zuul.eco-preprod.tsi-dev.otc-service.com
    http:
      paths:
      - path: /api/webhook/gitea
        pathType: Prefix
        backend:
          service:
            name: gitea-webhook-translator
            port:
              number: 80
