apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuul

resources:
- ../../base
- ingress.yaml
- secret.yaml

images:
- name: gitea-webhook-translator
  newName: quay.io/opentelekomcloud/gitea-webhook-translator
  newTag: "1.0.2"
