apiVersion: v1
kind: Secret
metadata:
  name: gitea-webhook-translator
type: Opaque
stringData:
  github-webhook-secret: <path:secret/data/zuul/connections/gitea#webhook_token>
  gitea-webhook-secret: <path:secret/data/zuul/connections/gitea#webhook_token>
