apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  template:
    spec:
      serviceAccount: "backstage"
      initContainers:
        - name: "vault-agent"
          command:
            - "sh"
            - "-c"
            - "vault agent -config=/etc/vault/vault-agent.hcl -exit-after-auth=true"
          env:
            - name: "VAULT_ADDR"
              value: "https://vault-lb.eco-preprod.tsi-dev.otc-service.com"
          image: "vault"
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          volumeMounts:
            - mountPath: "/etc/vault"
              name: "vault-agent-config"
            - mountPath: "/secrets"
              name: "secrets"

            - mountPath: "/var/run/secrets/tokens"
              name: "k8-tokens"
              readOnly: true

      containers:
        - name: backstage
          args:
            - "node"
            - "packages/backend"
            - "--config"
            - "app-config.yaml"
            - "--config"
            - "/secrets/app-config.production.yaml"
          volumeMounts:
           - mountPath: "/secrets"
             name: "secrets"

      volumes:
        - name: vault-agent-config
          configMap:
            defaultMode: 420
            name: backstage-vault-config

        - name: secrets
          emptyDir: {}

        - name: "k8-tokens"
          projected:
            defaultMode: 420
            sources:
            - serviceAccountToken:
                expirationSeconds: 7200
                path: "vault-token"
