apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: analytics-vault-config
    files:
      - vault-agent.hcl

images:
  - name: umami
    newName: quay.io/opentelekomcloud/umami
    newTag: "3.0.3"
