{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName | default (include "gitea.fullname" .) | quote }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName | quote }}
  {{- end }}
{{- end }}
