apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitea.runtimeSecrets.name | quote }}
type: Opaque
stringData:
  secret_key: {{ .Values.gitea.runtimeSecrets.secretKey | quote }}
  internal_token: {{ .Values.gitea.runtimeSecrets.internalToken | quote }}
