apiVersion: v1
kind: Secret
metadata:
  name: giji-jira-certs
type: Opaque
stringData:
  jira-cert.pem: <path:secret/data/jira/autoecobot#jira_pem>
  jira-key.pem: <path:secret/data/jira/autoecobot#jira_key>
