apiVersion: v1
kind: Secret
metadata:
  name: giji-demand-config
type: Opaque
stringData:
  JIRA_PROJECT_KEY_DEMAND: <path:secret/data/giji/config#jira_project_key_demand>
  JIRA_ISSUE_TYPE_ID_DEMAND: <path:secret/data/giji/config#jira_issue_type_id_demand>
  TARGET_SQUADS: <path:secret/data/giji/config#target_squads>
  IMPORTED_LABEL: <path:secret/data/giji/config#imported_label>
