apiVersion: v1
kind: Secret
metadata:
  name: giji-env
type: Opaque
stringData:
  GITHUB_TOKEN: <path:secret/data/github/otcbot#otcbot_giji_token>
  GITHUB_API_URL: <path:secret/data/helpcenter/monitoring/github#github_api_url>
  GITHUB_ORGS: <path:secret/data/helpcenter/monitoring/github#github_orgs>
  DB_HOST: <path:secret/data/helpcenter/monitoring/postgresql#host>
  DB_PORT: <path:secret/data/helpcenter/monitoring/postgresql#port>
  DB_CSV: <path:secret/data/helpcenter/monitoring/postgresql#dbname>
  DB_USER: <path:secret/data/helpcenter/monitoring/postgresql#username>
  DB_PASSWORD: <path:secret/data/helpcenter/monitoring/postgresql#password>
  BASE_GITEA_URL: <path:secret/data/gitea/config#gitea_address>
  JIRA_API_URL: <path:secret/data/jira/autoecobot#jira_api_url>
  JIRA_TOKEN: <path:secret/data/jira/autoecobot#jira_api_key>
  JIRA_CERT_PATH: /etc/giji/certs/jira-cert.pem
  JIRA_KEY_PATH: /etc/giji/certs/jira-key.pem
  DEH: <path:secret/data/giji/master_component#dedicated-host>
  ASG: <path:secret/data/giji/master_component#auto-scaling>
  ECS: <path:secret/data/giji/master_component#elastic-cloud-server>
  IMS: <path:secret/data/giji/master_component#image-management-service>
  BMS: <path:secret/data/giji/master_component#bare-metal-server>
  RDS: <path:secret/data/giji/master_component#relational-database-service>
  OPENGAUSS: <path:secret/data/giji/master_component#gaussdb-opengauss>
  GEMINIDB: <path:secret/data/giji/master_component#geminidb>
  MYSQL: <path:secret/data/giji/master_component#gaussdb-mysql>
  DRS: <path:secret/data/giji/master_component#data-replication-service>
  DAS: <path:secret/data/giji/master_component#data-admin-service>
  DDM: <path:secret/data/giji/master_component#distributed-database-middleware>
  DDS: <path:secret/data/giji/master_component#document-database-service>
