apiVersion: v1
kind: Secret
metadata:
  name: giji-bug-config
type: Opaque
stringData:
  JIRA_PROJECT_KEY: <path:secret/data/giji/config#jira_project_key>
  TARGET_SQUADS: <path:secret/data/giji/config#target_squads>
  IMPORTED_LABEL: <path:secret/data/giji/config#imported_label>
  JIRA_ISSUE_TYPE: <path:secret/data/giji/config#jira_issue_type>
