---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: "zookeeper-config"
    files:
      - scripts/ok
      - scripts/run
      - scripts/ready

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: "zookeeper"
      app.kubernetes.io/version: "3.8.0"
      app.kubernetes.io/part-of: "zuul"

images:
  - name: "zookeeper"
    newName: "quay.io/opentelekomcloud/zookeeper"
    newTag: "3.8.1"

resources:
  - cert.yaml
  - sa.yaml
  - service.yaml
  - statefulset.yaml
  - pdb.yaml
  - pvs.yaml
