---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-disk-retain
  csi:
    driver: disk.csi.everest.io
    fsType: ext4
    volumeAttributes:
      everest.io/disk-mode: SCSI
      everest.io/disk-volume-type: SAS
      everest.io/enterprise-project-id: "0"
      storage.kubernetes.io/csiProvisionerIdentity: everest-csi-provisioner
    volumeHandle: zookeeper-pv-0-volume-id
  claimRef:
    name: data-zookeeper-0
    namespace: zuul
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-disk-retain
  csi:
    driver: disk.csi.everest.io
    fsType: ext4
    volumeAttributes:
      everest.io/disk-mode: SCSI
      everest.io/disk-volume-type: SAS
      everest.io/enterprise-project-id: "0"
      storage.kubernetes.io/csiProvisionerIdentity: everest-csi-provisioner
    volumeHandle: zookeeper-pv-1-volume-id
  claimRef:
    name: data-zookeeper-1
    namespace: zuul
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persisteAttributes:
      everest.io/disk-mode: SCSI
      everest.io/disk-volume-type: SAS
      everest.io/enterprise-project-id: "0"
      storage.kubernetes.io/csiProvisionerIdentity: everest-csi-provisioner
    volumeHandle: zookeeper-pv-2-volume-id Retain
  storageClassName: csi-disk-retain
  csi:
    driver: disk.csi.everest.io
    fsType: ext4
    volumeHandle: zookeeper-pv-2
  claimRef:
    name: data-zookeeper-2
    namespace: zuul
