{{- if .Values.unsealer.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-unsealer-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-additional.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .Values.unsealer.secretName }}"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-unsealer-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-additional.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-unsealer-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.unsealer.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end }}
