  apiVersion: v2
  name: victoria-metrics-cluster
  description: A Helm chart for Kubernetes that includes Victoria Metrics Cluster
  version: 0.1.0
  dependencies:
    - name: victoria-metrics-cluster
      version: "0.12.1"
      repository: https://victoriametrics.github.io/helm-charts
