apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: outline

resources:
  - ../../../base
  - outline-anubis-ingress.yaml
  - outline-websockets-direct.yaml

patchesStrategicMerge:
  - patch-target.yaml
