apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline-websockets-direct
  namespace: outline
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: outline.eco-preprod.tsi-dev.otc-service.com
      http:
        paths:
          - path: /realtime
            pathType: Prefix
            backend:
              service:
                name: outline-wiki-preprod
                port:
                  number: 3000
          - path: /collaboration
            pathType: Prefix
            backend:
              service:
                name: outline-wiki-preprod
                port:
                  number: 3000
