apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline-anubis
  namespace: outline
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - secretName: outline-tls
      hosts:
        - outline.eco-preprod.tsi-dev.otc-service.com
  rules:
    - host: outline.eco-preprod.tsi-dev.otc-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anubis
                port:
                  number: 80
