apiVersion: v1
kind: ServiceAccount
metadata:
  name: anubis-vault-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anubis-role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: anubis-vault-auth
  namespace: helpcenter-swiss-archive