apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuul

resources:
  - ../../base
  - secret.yaml

images:
  - name: gitea-api-adapter
    newName: quay.io/opentelekomcloud/gitea-api-adapter
    newTag: "1.0.0"

commonLabels:
  environment: preprod
