apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for Kubernetes that includes kube-prometheus-stack and go-neb alert webhook
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "72.6.2"
    repository: "https://prometheus-community.github.io/helm-charts"
