---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dependencytrack-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: dependencytrack-api
  serviceName: "dependencytrack-api"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dependencytrack-api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: api
          image: dependencytrack/apiserver
          envFrom:
            - configMapRef:
                name: dependencytrack-api-config
            - secretRef:
                name: dependencytrack-db-credentials
                optional: true
            - secretRef:
                name: dependencytrack-oidc-credentials
                optional: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "4G"
              cpu: "1.0"
            limits:
              memory: "12G"
              cpu: "2.0"
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: dependencytrack-api-config
          configMap:
            defaultMode: 420
            name: dependencytrack-api-config

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
