---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cpn-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
    - host: cpn-api.eco-preprod.tsi-dev.otc-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cpn-backend-service
                port:
                  number: 8080
  tls:
    - hosts:
        - cpn-api.eco-preprod.tsi-dev.otc-service.com
      secretName: cpn-backend-tls
