---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cpn-front-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "100"
spec:
  rules:
    - host: cpn.eco-preprod.tsi-dev.otc-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anubis
                port:
                  number: 80
  tls:
    - hosts:
        - cpn.eco-preprod.tsi-dev.otc-service.com
      secretName: cpn-front-tls
