# OpenStack clouds configuration for production
# This file will be populated by ArgoCD Vault Plugin
clouds:
  production:
    auth:
      auth_url: <vault:secret/data/zuul/prod/openstack#auth_url>
      username: <vault:secret/data/zuul/prod/openstack#username>
      password: <vault:secret/data/zuul/prod/openstack#password>
      project_name: <vault:secret/data/zuul/prod/openstack#project_name>
      user_domain_name: <vault:secret/data/zuul/prod/openstack#user_domain_name>
      project_domain_name: <vault:secret/data/zuul/prod/openstack#project_domain_name>
    region_name: eu-de
    interface: public
    api_timeout: 60
    verify: true
