- job:
    name: system-config-run
    description: |
      Run the "base" playbook for system-config hosts.

      This is a parent job designed to be inherited.
    abstract: true
    pre-run: playbooks/zuul/run-base-pre.yaml
    run: playbooks/zuul/run-base.yaml
    post-run: playbooks/zuul/run-base-post.yaml
    vars:
      zuul_copy_output: "{{ copy_output | combine(host_copy_output | default({})) }}"
      stage_dir: "{{ ansible_user_dir }}/zuul-output"
      copy_output:
        '/var/log/syslog': logs_txt
        '/var/log/messages': logs_txt
        '/var/log/docker': logs
        '/var/log/containers': logs
      install_ansible_collections:
        - namespace: opentelekomcloud
          name: apimon
          repo: stackmon/ansible-collection-apimon
        - namespace: opentelekomcloud
          name: cloud
          repo: opentelekomcloud/ansible-collection-cloud
        - namespace: opentelekomcloud
          name: gitcontrol
          repo: opentelekomcloud/ansible-collection-gitcontrol
        - namespace: openstack
          name: cloud
          repo: openstack/ansible-collections-openstack
          git_provider: opendev.org
    required-projects:
      - name: github.com/opentelekomcloud/ansible-collection-cloud
        override-checkout: main
      - name: github.com/stackmon/ansible-collection-apimon
        override-checkout: main
      - name: github.com/opentelekomcloud/ansible-collection-gitcontrol
        override-checkout: main
      - name: opendev.org/openstack/ansible-collections-openstack
        override-checkout: master
    host-vars:
      bridge*.eco.tsi-dev.otc-service.com:
        install_ansible_collections:
          - namespace: opentelekomcloud
            name: apimon
            repo: stackmon/ansible-collection-apimon
          - namespace: opentelekomcloud
            name: cloud
            repo: opentelekomcloud/ansible-collection-cloud
          - namespace: opentelekomcloud
            name: gitcontrol
            repo: opentelekomcloud/ansible-collection-gitcontrol
          - namespace: openstack
            name: cloud
            repo: openstack/ansible-collections-openstack
            git_provider: opendev.org
        host_copy_output:
          '{{ zuul.project.src_dir }}/junit.xml': logs
          '{{ zuul.project.src_dir }}/test-results.html': logs
          '{{ zuul.project.src_dir }}/inventory/base/gate-hosts.yaml': logs
          '/var/log/screenshots': logs

- job:
    name: system-config-run-base
    parent: system-config-run
    description: |
      Run the "base" playbook on each of the node types
      currently in use.
    nodeset:
      nodes:
        - &bridge_node_x86 {name: bridge99.eco.tsi-dev.otc-service.com, label: ubuntu-jammy}
      groups:
        # Each job should define this group -- to avoid hard-coding
        # the bastion hostname in the job setup, playbooks/tasks refer
        # to it only by this group.  This should only have one entry
        # -- in a couple of places the jobs use the actual hostname
        # and assume element [0] here is that hostname.
        #
        # Note that this shouldn't be confused with the group in
        # inventory/service/groups.yaml -- this group contains the
        # host that Zuul, running on the executor, will setup as the
        # bridge node.  This node will then run a nested Ansible to
        # test the production playbooks -- *that* Ansible has a
        # "bastion" group too
        - &bastion_group { name: prod_bastion, nodes: [ bridge99.eco.tsi-dev.otc-service.com ] }
    files:
      - tox.ini
      - playbooks/
      - roles/
      - testinfra/

- job:
    name: system-config-run-statsd
    parent: system-config-run
    description: |
      Run the "statsd" playbook on each of the node types
      currently in use.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: statsd.centos-stream
          label: centos-9-stream
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-statsd.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/roles/statsd
      - testinfra/test_statsd.py

- job:
    name: system-config-run-x509-cert
    parent: system-config-run
    description: |
      Run the playbook for the x509 certificates.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/x509-certs.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/x509-certs.yaml
      - playbooks/roles/x509_cert

- job:
    name: system-config-run-apimon-epmon
    parent: system-config-run
    description: |
      Run the "apimon-epmon" playbook on each of the node types
      currently in use.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: epmon.centos-stream
          label: centos-9-stream
        - name: epmon.focal
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-apimon-epmon.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/templates/apimon
      - playbooks/zuul/templates/group_vars/apimon
      - playbooks/zuul/templates/host_vars/epmon
      - playbooks/service-apimon-epmon.yaml
      - testinfra/test_epmon.py

- job:
    name: system-config-run-apimon-scheduler
    parent: system-config-run
    description: |
      Run the "apimon-scheduler" playbook on each of the node types
      currently in use.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: scheduler.centos-stream
          label: centos-9-stream
        - name: scheduler.focal
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-apimon-scheduler.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/templates/apimon
      - playbooks/zuul/templates/group_vars/apimon
      - playbooks/service-apimon-scheduler.yaml
      - testinfra/test_scheduler.py

- job:
    name: system-config-run-apimon-executor
    parent: system-config-run
    description: |
      Run the "apimon-executor" playbook on each of the node types
      currently in use.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: executor.centos-stream
          label: centos-9-stream
        - name: executor.focal
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-apimon-executor.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/templates/apimon
      - playbooks/zuul/templates/group_vars/apimon
      - playbooks/service-apimon-executor.yaml
      - testinfra/test_executor.py

- job:
    name: system-config-run-graphite
    parent: system-config-run
    description: |
      Run the playbook for the graphite servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: graphite2.apimon.eco.tsi-dev.otc-service.com
          label: ubuntu-focal
        - name: graphite1.eco.tsi-dev.otc-service.com
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/acme-certs.yaml
        - playbooks/service-graphite.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/service-graphite.yaml
      - playbooks/roles/graphite
      - playbooks/roles/graphite_web
      - playbooks/zuul/templates/group_vars/graphite.yaml.j2
      - testinfra/test_graphite.py

- job:
    name: system-config-run-memcached
    parent: system-config-run
    description: |
      Run the playbook for the memcached servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: memcached.focal
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-memcached.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/service-memcached.yaml
      - playbooks/roles/memcached
      - testinfra/test_memcached.py

- job:
    name: system-config-run-alerta
    parent: system-config-run
    description: |
      Run the playbook for the alerta servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: alerta.focal
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-alerta.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/service-alerta.yaml
      - playbooks/roles/alerta/
      - testinfra/test_alerta.py

- job:
    name: system-config-run-grafana
    parent: system-config-run
    description: |
      Run the playbook for the grafana servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: grafana.focal
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-grafana.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/service-grafana.yaml
      - playbooks/roles/grafana/
      - testinfra/test_grafana.py

- job:
    name: system-config-run-acme-ssl
    parent: system-config-run
    description: |
      Run the playbook for the acme-ssl servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: le1
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/acme-certs.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/acme-ssl.yaml
      - playbooks/roles/acme_create_certs
      - playbooks/roles/acme_request_certs
      - playbooks/roles/acme_install_txt_records
      - playbooks/roles/acme_drop_txt_records

- job:
    name: system-config-run-proxy
    parent: system-config-run
    description: |
      Run the playbook for the proxy servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: proxy1.eco.tsi-dev.otc-service.com
          label: fedora-35
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/acme-certs.yaml
        - playbooks/service-proxy.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/service-proxy.yaml
      - playbooks/roles/haproxy
      # - inventory/service/group_vars/proxy.yaml

- job:
    name: system-config-run-vault
    parent: system-config-run
    description: |
      Run the playbook for the vault servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: vault1.eco.tsi-dev.otc-service.com
          label: ubuntu-focal
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        # We do not want to create CA part of ZK setup, therefore only invoke additional playbook in the test.
        - playbooks/acme-certs.yaml
        - playbooks/service-vault.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/service-vault.yaml
      - playbooks/roles/hashivault

- job:
    name: system-config-run-gitea
    parent: system-config-run
    description: |
      Run the playbook for the gitea servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: gitea.focal
          label: ubuntu-jammy
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-gitea.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/service-gitea.yaml
      - playbooks/roles/gitea/
      - testinfra/test_gitea.py

- job:
    name: system-config-run-keycloak
    parent: system-config-run
    description: |
      Run the playbook for the keycloak servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: keycloak.focal
          label: ubuntu-jammy
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        - playbooks/service-keycloak.yaml
    files:
      - playbooks/service-keycloak.yaml
      - playbooks/roles/keycloak/
      - testinfra/test_keycloak.py

- job:
    name: system-config-run-zookeeper
    parent: system-config-run
    description: |
      Run the playbook for the zk servers.
    nodeset:
      nodes:
        - <<: *bridge_node_x86
        - name: zk.centos-stream
          label: centos-9-stream
      groups:
        - <<: *bastion_group
    vars:
      run_playbooks:
        # We do not want to create CA part of ZK setup, therefore only invoke additional playbook in the test.
        - playbooks/x509-certs.yaml
        - playbooks/service-zookeeper.yaml
    files:
      - playbooks/bootstrap-bridge.yaml
      - playbooks/service-zookeeper.yaml
      - playbooks/roles/zookeeper
      - inventory/service/groups.yaml
