---
apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
  namespace: kube-system
  annotations:
    replicator.v1.mittwald.de/replicate-to: ".*"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "quay.io": {
          "auth": "<path:secret/data/image_registries/quay#auth>",
          "email": ""
        }
      }
    }
