apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cpn-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpn-backend
  serviceName: cpn-backend-service
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: cpn-backend
    spec:
      serviceAccountName: cpn
      terminationGracePeriodSeconds: 10
      containers:
      - name: cpn-backend
        image: quay.io/opentelekomcloud/circle-partner-navigator-backend
        ports:
        - containerPort: 8080
        command:
          ["/bin/sh", "-c"]
        args:
          ['source /secrets/cpn-env && npm run start']
        volumeMounts:
        - name: cpn-backend-persistent-storage
          mountPath: /opt/app/public/uploads
        - mountPath: "/secrets"
          name: "secrets"
      volumes:
      - name: secrets
        emptyDir: {}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cpn-backend-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: csi-disk-retain
        resources:
          requests:
            storage: 300Gi
