apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpn-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpn-front
  template:
    metadata:
      labels:
        app: cpn-front
    spec:
      containers:
        - name: cpn-front
          image: "quay.io/opentelekomcloud/circle-partner-navigator-frontend:change_1_latest"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cpn-front-nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: cpn-front-nginx.conf
              readOnly: true
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-logs
              mountPath: /var/log/nginx
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: cpn-front-nginx
          configMap:
            name: cpn-front-nginx
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-logs
          emptyDir: {}
