apiVersion: v2
name: promtail
description: A Helm chart for Kubernetes that includes promtail
version: 0.1.0
dependencies:
  - name: promtail
    version: "6.17.1"
    repository: "https://grafana.github.io/helm-charts"
