applications:
  - name: argocd-projects
    clusters: [preprod]
    config:
      namespace: argocd
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/helm_charts/local/argo-cd
      pluginName: argocd-vault-plugin-helm-with-args
      pluginEnv: '-f values/preprod/values-argocd-projects.yaml'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: argocd-clusters
    clusters: [preprod]
    config:
      namespace: argocd
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/helm_charts/local/argo-cd
      pluginName: argocd-vault-plugin-helm-with-args
      pluginEnv: '-f values/preprod/values-argocd-clusters.yaml'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: argocd-repositories
    clusters: [preprod]
    config:
      namespace: argocd
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/helm_charts/local/argo-cd
      pluginName: argocd-vault-plugin-helm-with-args
      pluginEnv: '-f values/preprod/values-argocd-repositories.yaml'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: argocd
    clusters: [preprod]
    config:
      namespace: argocd
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Enabling_docussaurus'
      path: kubernetes/helm_charts/upstream/argo-cd
      pluginName: argocd-vault-plugin-helm-with-args
      pluginEnv: '-f values-preprod.yaml'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: argocd-additional-manifests
    clusters: [preprod]
    config:
      namespace: argocd
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/helm_charts/local/argo-cd
      pluginName: argocd-vault-plugin-helm-with-args
      pluginEnv: '-f values/preprod/values-argocd-additional-manifests.yaml'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: cert-manager
    clusters: [preprod]
    config:
      namespace: cert-manager
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/helm_charts/upstream/cert-manager
      pluginName: argocd-vault-plugin-helm-with-args
      pluginEnv: '-f values.yaml --set installCRDs=true'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: cert-manager-additional-manifests
    clusters: [preprod]
    config:
      namespace: cert-manager
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/helm_charts/local/cert-manager
      pluginName: argocd-vault-plugin-helm-with-args
      pluginEnv: '-f values.yaml'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: grafana
    clusters: [preprod]
    config:
      namespace: grafana-infra
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/helm_charts/upstream/grafana
      pluginName: argocd-vault-plugin-helm
      pluginEnv: '-f values-preprod.yaml'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: outline-wiki-additional-manifests
    clusters: [preprod]
    config:
      namespace: outline
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Enabling_docussaurus'
      path: kubernetes/helm_charts/local/outline
      pluginName: argocd-vault-plugin-helm
      pluginEnv: '-f values-preprod.yaml'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: outline-wiki
    clusters: [preprod]
    config:
      namespace: outline
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Enabling_docussaurus'
      path: kubernetes/helm_charts/upstream/outline
      pluginName: argocd-vault-plugin-helm
      pluginEnv: '-f values-preprod.yaml'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  # - name: victoria-metrics-auth
  #   clusters: [preprod]
  #   config:
  #     namespace: monitoring
  #     repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
  #     targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
  #     path: kubernetes/helm_charts/upstream/victoria-metrics-auth
  #     pluginName: argocd-vault-plugin-helm
  #     pluginEnv: '-f values-preprod.yaml'
  #     project: infra
  #     syncPolicy:
  #       automated:
  #         prune: true
  #         selfHeal: true
  #       syncOptions:
  #         - CreateNamespace=true

  # - name: promtail
  #   clusters: [preprod]
  #   config:
  #     namespace: promtail
  #     repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
  #     targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
  #     path: kubernetes/helm_charts/upstream/promtail
  #     pluginName: argocd-vault-plugin-helm
  #     pluginEnv: '-f values-preprod.yaml'
  #     project: infra
  #     syncPolicy:
  #       automated:
  #         prune: true
  #         selfHeal: true
  #       syncOptions:
  #         - CreateNamespace=true

  # - name: cert-exporter
  #   clusters: [preprod]
  #   config:
  #     namespace: cert-manager
  #     repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
  #     targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
  #     path: kubernetes/helm_charts/upstream/cert-exporter
  #     pluginName: argocd-vault-plugin-helm
  #     pluginEnv: '-f values.yaml'
  #     project: infra
  #     syncPolicy:
  #       automated:
  #         prune: true
  #         selfHeal: true
  #       syncOptions:
  #         - CreateNamespace=true


#####################################
########## KUSTOMIZE APPS ###########
#####################################

  - name: kustomize-backstage-dev
    clusters: [preprod]
    config:
      namespace: backstage-dev
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/kustomize/backstage/overlays/dev/
      project: infra
      kustomize: {}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: openapi-validator
    clusters: [preprod]
    config:
      namespace: openapi-validator
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'Helm_charts_restructure&Pre-Prod_setup'
      path: kubernetes/kustomize/openapi-validator/overlays/dev/
      pluginName: argocd-vault-plugin-kustomize
      pluginEnv: '.'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - name: giji
    clusters: [preprod]
    config:
      namespace: giji
      repoURL: 'https://github.com/opentelekomcloud-infra/system-config.git'
      targetRevision: 'giji_first_build'
      path: kubernetes/kustomize/giji/base/
      pluginName: argocd-vault-plugin-kustomize
      pluginEnv: '.'
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
