image: "Standard_Ubuntu_22.04_latest"
flavor: "c4.xlarge.4"
security_groups: ["common_sg", "gitea_sg"]
nics:
  - fixed_ip: "192.168.150.200"
    net-name: "eco-infra-net"
root_volume_size: 20
auto_ip: false

data_volumes:
  - name: "var"
    size: 100
  - name: "home"
    size: 20
  - name: "gitea1"
    size: 1024
    type: "SAS"
userdata: |
  #cloud-config
  disk_setup:
    /dev/vdb:
      table_type: 'mbr'
      layout:
        - 100
    /dev/vdc:
      table_type: 'mbr'
      layout:
        - 100
    /dev/vdd:
      table_type: 'mbr'
      layout:
        - 100
  fs_setup:
    - label: var
      filesystem: ext4
      device: '/dev/vdb1'
    - label: home
      filesystem: ext4
      device: '/dev/vdc1'
    - label: gitea1
      filesystem: ext4
      device: '/dev/vdd1'
  mounts:
    - [ "LABEL=home", "/home", "auto", "defaults", "0", "2" ]
  groups:
    - automation
  users:
    - default
    - name: automation
      primary_group: automation
      ssh_authorized_keys:
        - "{{ bastion_public_key }}"
      sudo: ALL=(ALL) NOPASSWD:ALL
  runcmd:
    - mkdir /mnt/vdb && mount /dev/vdb1 /mnt/vdb
    - cp -a /var/* /mnt/vdb/
    - umount /mnt/vdb && rmdir /mnt/vdb
    - echo "LABEL=var   /var   auto   defaults,comment=cloudconfig  0 2" >> /etc/fstab
    - echo "LABEL=gitea1   /var/lib/gitea   auto   defaults  0 2" >> /etc/fstab
    - mount /var
    - mkdir -p /var/lib/gitea
    - mount /var/lib/gitea

ssl_certs:
  gitea:
    - "gitea2.eco.tsi-dev.otc-service.com"
    - "gitea.eco.tsi-dev.otc-service.com"
gitea_cert: "gitea"

firewalld_extra_services_enable: ['https']
firewalld_extra_ports_enable: ['2222/tcp']