image: "Standard_Debian_11_latest"
flavor: "c4.xlarge.4"
security_groups: ["common_sg", "vault_sg"]
nics:
  - fixed_ip: "192.168.150.123"
    net-name: "eco-infra-net"
root_volume_size: 20
auto_ip: false

ssl_certs:
  vault:
    - "vault2.eco.tsi-dev.otc-service.com"
vault_cert: "vault"

vault_seal_transit_address: "https://vault.eco.tsi-dev.otc-service.com:8200"

firewalld_extra_ports_enable: ['8200/tcp', '8201/tcp']
