{{- if and (eq .Values.mode "cluster") .Values.storage.enabled .Values.storage.persistence.enabled .Values.storage.persistence.sharedNFS }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "swift-proxy.fullname" . }}-storage-pv
  labels:
    {{- include "swift-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  capacity:
    storage: {{ .Values.storage.persistence.size }}
  accessModes:
    - {{ .Values.storage.persistence.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.storage.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.storage.persistence.storageClass }}
  mountOptions:
    {{- toYaml .Values.storage.persistence.sharedNFS.mountOptions | nindent 4 }}
  nfs:
    server: {{ .Values.storage.persistence.sharedNFS.server }}
    path: {{ .Values.storage.persistence.sharedNFS.path }}
{{- end }}
