apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swift-proxy.fullname" . }}-clouds
  labels:
    {{- include "swift-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  clouds.yaml: |
    {{- .Values.clouds | nindent 4 }}
