apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openapi-validator
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-rpm: "1m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-size: "4096"
    cert-manager.io/private-key-rotation-policy: Always
spec:
  ingressClassName: nginx
  rules:
    - host: openapi-validator.eco.tsi-dev.otc-service.com
      http:
        paths:
          - backend:
              service:
                name: openapi-validator-svc
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - openapi-validator.eco.tsi-dev.otc-service.com
      secretName: openapi-validator-tls-cert
