apiVersion: v1
kind: Secret
metadata:
  name: openapi-validator-secret
type: Opaque
stringData:
  GITEA_BASE_URL: <path:secret/data/gitea/config#gitea_address>
  GITEA_TOKEN: <path:secret/data/openapi-validator/git-connection#gitea_token>
  REPORTPORTAL_ENDPOINT: <path:secret/data/reportportal/ecobot#endpoint>
  REPORTPORTAL_API_KEY: <path:secret/data/reportportal/ecobot#token>
