apiVersion: v1
kind: Secret
metadata:
  name: openapi-validator-secret
type: Opaque
stringData:
  GITEA_BASE_URL: <path:secret/data/gitea/config#gitea_address>
  GITEA_TOKEN: <path:secret/data/openapi-validator/git-connection#gitea_token>
  REPORTPORTAL_ENDPOINT: <path:secret/data/reportportal/ecobot#endpoint>
  REPORTPORTAL_API_KEY: <path:secret/data/reportportal/ecobot#token>
  AUTH_SECRET: <path:secret/data/openapi-validator/zitadel-connection#zitadel_auth_secret>
  APP_URL: <path:secret/data/openapi-validator/zitadel-connection#app_url>
  AUTH_ZITADEL_ISSUER: <path:secret/data/openapi-validator/zitadel-connection#zitadel_auth_issuer>
  AUTH_ZITADEL_ID: <path:secret/data/openapi-validator/zitadel-connection#zitade_auth_id>
  ZITADEL_INTROSPECTION_CLIENT_ID: <path:secret/data/openapi-validator/zitadel-connection#introspection_client_id>
  ZITADEL_INTROSPECTION_CLIENT_SECRET: <path:secret/data/openapi-validator/zitadel-connection#introspection_client_secret>
  ZITADEL_X_INTERNAL_API_KEY: <path:secret/data/openapi-validator/zitadel-connection#internal_api_key>
  ZITADEL_MACHINE_SECRET: <path:secret/data/openapi-validator/zitadel-connection#zitadel_machine_secret>
  ZITADEL_MACHINE_ID: <path:secret/data/openapi-validator/zitadel-connection#zitadel_machine_id>
  ZITADEL_PROJECT_ID: <path:secret/data/openapi-validator/zitadel-connection#zitadel_project_id>
