apiVersion: batch/v1
kind: CronJob
metadata:
  name: eyes-on-docs-eco-issues
spec:
  concurrencyPolicy: Forbid
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: "eyes-on-docs"
          restartPolicy: OnFailure
          initContainers:
            - name: "vault-agent"
              command:
                - "sh"
                - "-c"
                - "vault agent -config=/etc/vault/vault-agent.hcl -exit-after-auth=true"
              env:
                - name: "VAULT_ADDR"
                  value: "https://vault-lb.eco.tsi-dev.otc-service.com:8200"
              image: "hashicorp/vault"
              resources:
                limits:
                  cpu: "100m"
                  memory: "100Mi"
                requests:
                  cpu: "50m"
                  memory: "50Mi"
              volumeMounts:
                - mountPath: "/etc/vault"
                  name: "vault-agent-config"
                - mountPath: "/secrets"
                  name: "secrets"
                - mountPath: "/var/run/secrets/tokens"
                  name: "k8-tokens"
                  readOnly: true

          containers:
            - name: eyes-on-docs-eco-issues
              image: quay.io/opentelekomcloud/eyes-on-docs
              imagePullPolicy: IfNotPresent
              command:
              - "/bin/sh"
              - "-c"
              - "source /secrets/gdm-env; python3 main.py --eod8"
              volumeMounts:
                - mountPath: "/secrets"
                  name: "secrets"
          volumes:
            - name: vault-agent-config
              configMap:
                defaultMode: 420
                name: eyes-on-docs-vault-config
            - name: secrets
              emptyDir: {}
            - name: "k8-tokens"
              projected:
                defaultMode: 420
                sources:
                - serviceAccountToken:
                    expirationSeconds: 7200
                    path: "vault-token"
