apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: "base"
      app.kubernetes.io/managed-by: "kustomize"

images:
  - name: "quay.io/opentelekomcloud/eyes_on_docs"
    newTag: "release_0.0.1"

resources:
  - cronjob-1-servicesdict.yaml
  - cronjob-2-gt.yaml
  - cronjob-3-gh.yaml
  - cronjob-4-fz.yaml
  - cronjob-5-oi.yaml
  - cronjob-6-lci.yaml
  - cronjob-7-rch.yaml
  - cronjob-8-ei.yaml
  - cronjob-9-scheduler.yaml
  - sa.yaml
