apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helpcenter-swiss-public

resources:
  - ../../../base
  - service-account.yaml

patchesStrategicMerge:
  - patch-target.yaml

configMapGenerator:
  - name: vault-agent-config
    files:
      - vault-agent.hcl
