apiVersion: v2
name: victoria-metrics-auth
description: A Helm chart for Kubernetes that includes Victoria Auth Proxy
version: 0.1.0
dependencies:
  - name: victoria-metrics-auth
    version: "0.24.0"
    repository: https://victoriametrics.github.io/helm-charts
