apiVersion: v2
name: gitea
description: A Helm chart for Gitea
type: application
version: 0.1.0
appVersion: "1.24.7"
home: https://gitea.io
keywords:
  - gitea
  - git
  - scm
  - source-control
  - version-control
maintainers:
  - name: OTC Infrastructure Team
sources:
  - https://github.com/go-gitea/gitea
  - https://github.com/gitea/helm-chart
