apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-size: "4096"
    cert-manager.io/private-key-rotation-policy: Always
spec:
  ingressClassName: nginx
  rules:
  - host: analytics.otc-service.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anubis
            port:
              number: 8080
  tls:
    - hosts:
        - analytics.otc-service.com
      secretName: analytics-tls
