apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: zuul-config
  labels:
    app.kubernetes.io/name: "zuul"
    app.kubernetes.io/component: "zuul-config"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: zuul-config-sfs-turbo
  storageClassName: csi-sfsturbo-retain
