---
apiVersion: v1
kind: Secret
metadata:
  name: swift-proxy-config
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      logs:
        auth:
          auth_url: "placeholder"
          username: "placeholder"
          password: "placeholder"
          project_domain_id: "placeholder"
          project_name: "placeholder"
          user_domain_name: "placeholder"
        auth_type: "placeholder"
        object_store_endpoint_override: "placeholder""
