apiVersion: v1
kind: Secret
metadata:
  name: zitadel-db-ssl-ca-crt
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.dbSslCaCrt | b64enc | quote }}
