zuul_main_vars:
  zookeeper_instance_group: "zuul-zookeeper"
  graphite_host: "192.168.14.241"
  statsd_host: "zuul-statsd-main"
  config_repo: "https://github.com/opentelekomcloud-infra/zuul-config.git"
  web_domain: "zuul.otc-service.com"
  nodepool_version_tag: "6.1.0"
  zuul_version_tag: "6.1.0"
  zuul_connections:
    - name: "github"
      driver: "github"
    - name: "gitlab"
      driver: "gitlab"
      canonical_hostname: "gitlab"
    - name: "opendev"
      driver: "git"
      baseurl: "https://opendev.org"
  vault_image: "vault:1.10.0"

zuul_instances:
  main:
    zookeeper_instance_group: "{{ zuul_main_vars.zookeeper_instance_group }}"
    graphite_host: "{{ zuul_main_vars.graphite_host }}"
    statsd_host: "{{ zuul_main_vars.statsd_host }}"
    config_repo: "{{ zuul_main_vars.config_repo }}"
    web_domain: "{{ zuul_main_vars.web_domain }}"
    nodepool_version_tag: "{{ zuul_main_vars.nodepool_version_tag }}"
    zuul_version_tag: "{{ zuul_main_vars.zuul_version_tag }}"
    zuul_connections: "{{ zuul_main_vars.zuul_connections }}"
    vault_image: "{{ zuul_main_vars.vault_image }}"
    zuul_web_instances_count: 0
    zuul_scheduler_instances_count: 0
    zuul_merger_instances_count: 0
    zuul_executor_instances_count: 0
    nodepool_launcher_instances_count: 0
    nodepool_builder_instances_count: 0

  infra:
    zookeeper_instance_group: "{{ zuul_main_vars.zookeeper_instance_group }}"
    graphite_host: "{{ zuul_main_vars['graphite_host'] }}"
    statsd_host: "{{ zuul_main_vars.statsd_host }}"
    config_repo: "{{ zuul_main_vars.config_repo }}"
    web_domain: "{{ zuul_main_vars.web_domain }}"
    nodepool_version_tag: "{{ zuul_main_vars.nodepool_version_tag }}"
    zuul_version_tag: "{{ zuul_main_vars.zuul_version_tag }}"
    zuul_connections: "{{ zuul_main_vars.zuul_connections }}"
    vault_image: "{{ zuul_main_vars.vault_image }}"
    zuul_web_instances_count: 2
    zuul_scheduler_instances_count: 1
    zuul_merger_instances_count: 1
    zuul_executor_instances_count: 2
    nodepool_launcher_instances_count: 1
    nodepool_builder_instances_count: 1
    ingress_class: "nginx"

  infra2:
    zookeeper_instance_group: "{{ zuul_main_vars.zookeeper_instance_group }}"
    graphite_host: "{{ zuul_main_vars.graphite_host }}"
    statsd_host: "{{ zuul_main_vars.statsd_host }}"
    config_repo: "{{ zuul_main_vars.config_repo }}"
    web_domain: "{{ zuul_main_vars.web_domain }}"
    nodepool_version_tag: "{{ zuul_main_vars.nodepool_version_tag }}"
    zuul_version_tag: "{{ zuul_main_vars.zuul_version_tag }}"
    zuul_connections: "{{ zuul_main_vars.zuul_connections }}"
    vault_image: "{{ zuul_main_vars.vault_image }}"
    zuul_web_instances_count: 0
    zuul_scheduler_instances_count: 0
    zuul_merger_instances_count: 0
    zuul_executor_instances_count: 0
    nodepool_launcher_instances_count: 0
    nodepool_builder_instances_count: 0
    ingress_class: "nginx"

zuul_k8s_instances:
  # - zuul_instance: "main"
  #   context: "otcci"
  #   instance: "main"
  #   namespace: "zuul-ci"
  - zuul_instance: "infra"
    context: "otcinfra"
    instance: "main"
    namespace: "zuul-ci"
  - zuul_instance: "infra2"
    context: "otcinfra2"
    instance: "main"
    namespace: "zuul-ci"
