---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nginx-config
    files:
      - configs/nginx-site.conf
      - templates/404.html

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: "base"
      app.kubernetes.io/managed-by: "kustomize"

images:
  - name: "docker.io/nginxinc/nginx-unprivileged"
    newName: "nginx"
    newTag: "alpine3.20"

resources:
  - sa.yaml
  - role.yaml
  - role_binding.yaml
  - deployment.yaml
  - service.yaml
