---
apiVersion: v1
kind: Secret
metadata:
  name: swift-proxy-config
stringData:
  clouds.yaml: |
    clouds:
      logs:
        auth:
          auth_url: <path:openstack/static-creds/cloud_449_de_hc_int_swiss#auth.auth_url>
          username: <path:openstack/static-creds/cloud_449_de_hc_int_swiss#auth.username>
          password: <path:openstack/static-creds/cloud_449_de_hc_int_swiss#auth.password>
          project_domain_id: <path:openstack/static-creds/cloud_449_de_hc_int_swiss#auth.project_domain_id>
          project_name: <path:openstack/static-creds/cloud_449_de_hc_int_swiss#auth.project_name>
          user_domain_name: <path:openstack/static-creds/cloud_449_de_hc_int_swiss#auth.user_domain_name>
        auth_type: <path:openstack/static-creds/cloud_449_de_hc_int_swiss#auth_type>
        # object_store_endpoint_override: <path:openstack/static-creds/cloud_449_de_hc_int_swiss#object_store_endpoint_override>
