apiVersion: v1
kind: Service
metadata:
  name: backstage-oauth-proxy
  labels:
    app.kubernetes.io/component: oauth-proxy
spec:
  selector:
    app.kubernetes.io/component: oauth-proxy
  ports:
    - name: http
      port: 80
      targetPort: 4180
