---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dependencytrack-api
  namespace: dependencytrack-preprod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: dependencytrack-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dependencytrack-frontend
  namespace: dependencytrack-preprod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: dependencytrack-frontend
