---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dependencytrack
  namespace: dependencytrack-preprod
  labels:
    app.kubernetes.io/name: dependencytrack
    app.kubernetes.io/environment: preprod
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dependencytrack
  namespace: dependencytrack-preprod
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dependencytrack
  namespace: dependencytrack-preprod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dependencytrack
subjects:
  - kind: ServiceAccount
    name: dependencytrack
    namespace: dependencytrack-preprod
