---
apiVersion: v1
kind: Service
metadata:
  name: zuul-web
  labels:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-web
spec:
  type: "ClusterIP"
  ports:
    - name: "web"
      port: 9000
      protocol: "TCP"
      targetPort: "web"
  selector:
    app.kubernetes.io/name: "zuul"
    app.kubernetes.io/part-of: "zuul"
    app.kubernetes.io/component: "zuul-web"
