apiVersion: v2
name: cert-manager
description: A Helm chart for managing Cert Manager with custom ClusterIssuers
version: 0.1.0
dependencies:
  - name: cert-manager
    version: "v1.19.3"
    repository: "https://charts.jetstack.io"
