distro_packages:
  - dnsutils
  - emacs23-nox
  - yaml-mode
  - iputils-ping
  - vim-nox
  - unattended-upgrades
  - mailutils
  - auditd
sftp_path: /usr/lib/openssh/sftp-server
ssh_service_name: ssh
