container_runtime: "/usr/bin/{{ container_command }}"

keycloak_os_group: keycloak
keycloak_os_user: keycloak

keyclok_image: quay.io/keycloak/keycloak:26.2
keycloak_postgres_image: quay.io/opentelekomcloud/postgres:15.12

keycloak_enable_https: true

keycloak_run_local_postgres: false
keycloak_postgres_user: keycloak
keycloak_postgres_password: dummy
keycloak_postgres_db: keycloak
