---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../components/ca
  - ../components/zookeeper
  - ../components/zuul-config
  - ../components/zuul-executor
  - ../components/zuul-scheduler
  - ../components/zuul-web
  - ../components/nodepool-launcher

configMapGenerator:
  - name: "zuul-executor-vars"
    literals: []

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: "base"
      app.kubernetes.io/managed-by: "kustomize"

# images:

resources:
  - sa.yaml
  - cert.yaml

secretGenerator:
  - name: "zuul-config"
    files:
      - "configs/zuul.conf"
  - name: "nodepool-config"
    files: []
