---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuul

components:
  - ../../../base

namePrefix: zuul-

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: zuul-oauth-proxy
      app.kubernetes.io/environment: preprod

patches:
  - path: ingress-patch.yaml
  - path: secret-patch.yaml
