apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  project: system-config
  source:
    path: kubernetes/backstage/overlays/prod
    repoURL: https://github.com/opentelekomcloud-infra/system-config
    targetRevision: kustomize
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - PruneLast=true
