- hosts: alerta-k8s:!disabled
  name: "Configure Alerta in K8s"
  tasks:
    - include_role:
        name: alerta_k8s
      vars:
        alerta: "{{ alerta_instances[item.alerta_instance] | combine(alerta_instances_secrets[item.alerta_instance], recursive=True) }}"
        instance: "{{ item.instance }}"
        context: "{{ item.context }}"
        namespace: "{{ item.namespace }}"
      loop: "{{ alerta_k8s_instances | list }}"
