apiVersion: v1
kind: Service
metadata:
  name: gitea-api-adapter
  labels:
    app: gitea-api-adapter
spec:
  selector:
    app: gitea-api-adapter
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
