apiVersion: v1
kind: Service
metadata:
  name: gitea-api-adapter
  labels:
    app: gitea-api-adapter
spec:
  selector:
    app: gitea-api-adapter
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  type: ClusterIP
