apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcaptcha
  annotations:
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-connections: "50"
spec:
  rules:
  - host: mcaptcha.eco-preprod.tsi-dev.otc-service.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mcaptcha
            port:
              number: 80
  tls:
  - hosts:
    - mcaptcha.eco-preprod.tsi-dev.otc-service.com
    secretName: mcaptcha-tls
