---
apiVersion: v1
kind: Namespace
metadata:
  name: mcaptcha
  labels:
    app.kubernetes.io/name: mcaptcha
    app.kubernetes.io/instance: preprod
    environment: preprod
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
