apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anubis-hc-archive
  namespace: argocd
spec:
  destination:
    namespace: hc-archive
    server: https://192.168.170.211:5443
  project: infra
  source:
    path: kubernetes/kustomize/anubis/overlays/prod/helpcenter_archive
    repoURL: https://github.com/opentelekomcloud-infra/system-config
    targetRevision: anubis-hc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
