apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anubis-hc-swiss-internal
  namespace: argocd
spec:
  destination:
    namespace: helpcenter-swiss-int
    server: https://192.168.170.211:5443
  project: infra
  source:
    path: kubernetes/kustomize/anubis/overlays/prod/helpcenter_swiss_internal
    repoURL: https://github.com/opentelekomcloud-infra/system-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
