---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "zuul-admin-crb-preprod"
roleRef:
  kind: "ClusterRole"
  name: "cluster-admin"
  apiGroup: ""
subjects:
  - kind: "ServiceAccount"
    name: "zuul"
    namespace: "zuul-preprod"
