---
# Mount nodepool config for launcher
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodepool-launcher
spec:
  template:
    spec:
      volumes:
        - name: nodepool-config-yaml
          configMap:
            name: nodepool-config-yaml
      containers:
        - name: nodepool-launcher
          image: quay.io/opentelekomcloud/nodepool-launcher:8.2.0
          volumeMounts:
            - name: nodepool-config-yaml
              mountPath: /etc/nodepool/nodepool.yaml
              subPath: nodepool.yaml
              readOnly: true
