---
- op: remove
  path: /spec/template/spec/nodeSelector
  target:
    kind: Deployment
    name: zuul-scheduler
---
- op: remove
  path: /spec/template/spec/nodeSelector
  target:
    kind: Deployment
    name: zuul-web
---
- op: remove
  path: /spec/template/spec/nodeSelector
  target:
    kind: Deployment
    name: zuul-merger
---
- op: remove
  path: /spec/template/spec/nodeSelector
  target:
    kind: Deployment
    name: zuul-client
---
- op: remove
  path: /spec/template/spec/nodeSelector
  target:
    kind: Deployment
    name: zuul-config
---
- op: remove
  path: /spec/template/spec/nodeSelector
  target:
    kind: Deployment
    name: nodepool-launcher
