---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zuul-web-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-size: "4096"
    cert-manager.io/private-key-rotation-policy: Always
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/priority: "100"
spec:
  ingressClassName: nginx
  rules:
    - host: api.zuul.eco-preprod.tsi-dev.otc-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zuul-web
                port:
                  number: 9000
  tls:
    - hosts:
        - api.zuul.eco-preprod.tsi-dev.otc-service.com
      secretName: zuul-preprod-api-cert
