---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zuul-merger-gitconfig
  namespace: zuul
data:
  gitconfig: |
    # Rewrite git URLs for Gitea infra organization
    # When Zuul tries ssh://git@github.com/infra/*, redirect to Gitea
    [url "ssh://git@gitea.eco.tsi-dev.otc-service.com:2222/infra/"]
        insteadOf = ssh://git@github.com/infra/
