---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zuul-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-size: "4096"
    cert-manager.io/private-key-rotation-policy: Always
    nginx.ingress.kubernetes.io/auth-url: "https://zuul-oauth2-proxy.eco-preprod.tsi-dev.otc-service.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://zuul-oauth2-proxy.eco-preprod.tsi-dev.otc-service.com/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token"
spec:
  ingressClassName: nginx
  rules:
    - host: zuul.eco-preprod.tsi-dev.otc-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zuul-web
                port:
                  number: 9000
  tls:
    - hosts:
        - zuul.eco-preprod.tsi-dev.otc-service.com
      secretName: zuul-preprod-cert
