---
# Mount SSH keys and builds directory for web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-web
spec:
  template:
    spec:
      volumes:
        - name: zuul-ssh-keys
          secret:
            secretName: zuul-ssh-keys
            defaultMode: 0600
        - name: zuul-builds
          persistentVolumeClaim:
            claimName: zuul-builds
      containers:
        - name: zuul
          image: zuul/zuul-web
          volumeMounts:
            - name: zuul-ssh-keys
              mountPath: /var/lib/zuul-ssh
              readOnly: true
            - name: zuul-builds
              mountPath: /var/lib/zuul/builds
              readOnly: true
