---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zuul-builds
  labels:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/component: shared-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sfs-turbo
  resources:
    requests:
      storage: 100Gi
