---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-scheduler
spec:
  template:
    spec:
      volumes:
        - name: zuul-tenants
          configMap:
            name: zuul-tenants
      containers:
        - name: zuul-scheduler
          volumeMounts:
            - name: zuul-tenants
              mountPath: /etc/zuul-config/tenants
              readOnly: true
