---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-scheduler
spec:
  template:
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "api.github.com"
      securityContext:
        fsGroup: 10001
      volumes:
        - name: zuul-ssh-keys
          secret:
            secretName: zuul-ssh-keys
            defaultMode: 0400
        - name: tenant-config
          configMap:
            name: nodepool-config-yaml
            items:
              - key: main.yaml
                path: preprod/main.yaml
        - name: envoy-config
          configMap:
            name: envoy-config
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.28-latest
          args:
            - -c
            - /etc/envoy/envoy.yaml
          ports:
            - containerPort: 443
              name: proxy
              protocol: TCP
            - containerPort: 9901
              name: admin
              protocol: TCP
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
        - name: zuul
          image: zuul/zuul-scheduler
          volumeMounts:
            - name: zuul-ssh-keys
              mountPath: /var/lib/zuul-ssh
              readOnly: true
            - name: tenant-config
              mountPath: /etc/zuul-config/tenants
              readOnly: true
