---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-scheduler
spec:
  template:
    spec:
      hostAliases:
        - ip: "10.247.122.183"
          hostnames:
            - "api.github.com"
      securityContext:
        fsGroup: 10001
      volumes:
        - name: zuul-ssh-keys
          secret:
            secretName: zuul-ssh-keys
            defaultMode: 0400
        - name: tenant-config
          configMap:
            name: nodepool-config-yaml
            items:
              - key: main.yaml
                path: preprod/main.yaml
      containers:
        - name: zuul
          image: zuul/zuul-scheduler
          volumeMounts:
            - name: zuul-ssh-keys
              mountPath: /var/lib/zuul-ssh
              readOnly: true
            - name: tenant-config
              mountPath: /etc/zuul-config/tenants
              readOnly: true
