---
# Mount SSH keys for merger
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-merger
spec:
  template:
    spec:
      securityContext:
        fsGroup: 10001
      volumes:
        - name: zuul-ssh-keys
          secret:
            secretName: zuul-ssh-keys
            defaultMode: 0400
        - name: gitconfig
          configMap:
            name: zuul-merger-gitconfig
      containers:
        - name: zuul
          image: zuul/zuul-merger
          volumeMounts:
            - name: zuul-ssh-keys
              mountPath: /var/lib/zuul-ssh
              readOnly: true
            - name: gitconfig
              mountPath: /var/lib/zuul/.gitconfig
              subPath: gitconfig
              readOnly: true
