---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zuul-merger-ssh-config
data:
  config: |
    Host gitea.eco.tsi-dev.otc-service.com
        Port 2222
        User git
        IdentityFile /var/lib/zuul-ssh/gitea.key
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
