apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis
spec:
  template:
    spec:
      serviceAccountName: anubis-vault-auth
      initContainers:
        - name: "vault-agent"
          command:
            - "sh"
            - "-c"
            - "vault agent -config=/etc/vault/vault-agent.hcl -exit-after-auth=true"
          env:
            - name: "VAULT_ADDR"
              value: "https://vault-lb.eco.tsi-dev.otc-service.com:8200"
          image: "hashicorp/vault"
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          volumeMounts:
            - mountPath: "/etc/vault"
              name: "vault-agent-config"
            - mountPath: "/secrets"
              name: "secrets"
            - mountPath: "/var/run/secrets/tokens"
              name: "k8-tokens"
              readOnly: true
      volumes:
        - name: vault-agent-config
          configMap:
            defaultMode: 420
            name: vault-agent-config

        - name: secrets
          emptyDir: {}

        - name: "k8-tokens"
          projected:
            defaultMode: 420
            sources:
            - serviceAccountToken:
                expirationSeconds: 7200
                path: "vault-token"

      containers:
        - name: anubis
          volumeMounts:
            - name: secrets
              mountPath: "/secrets"
              readOnly: true
          env:
            - name: TARGET
              value: "http://helpcenter-swiss-frontend"

        - name: vault-agent-sidecar
          image: hashicorp/vault:latest
          command: ["/bin/vault"]
          args:
            - agent
            - -config=/vault/config/vault-agent.hcl
          env:
            - name: VAULT_ADDR
              value: "https://vault-lb.eco.tsi-dev.otc-service.com:8200"
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: secrets
              mountPath: /secrets
            - name: vault-token
              mountPath: /var/run/secrets/tokens
