apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: prod

namespace: dependencytrack

components:
  - ../../components/postgres

patches:
  - patch: |-
      - op: replace
        path: /spec/ingressClassName
        value:
          nginx
      - op: replace
        path: /spec/rules/0/host
        value:
          dependencytrack.eco.tsi-dev.otc-service.com
      - op: replace
        path: /metadata/annotations
        value:
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          cert-manager.io/private-key-algorithm: RSA
          cert-manager.io/private-key-size: "4096"
          cert-manager.io/private-key-rotation-policy: Always
      - op: replace
        path: /spec/tls
        value:
          - hosts:
              - dependencytrack.eco.tsi-dev.otc-service.com
            secretName: dependencytrack-cert-prod
    target:
      group: networking.k8s.io
      kind: Ingress
      name: dependencytrack
      version: v1

  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccount
        value:
          "dependencytrack"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value:
          "csi-disk-retain"
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/volumeName
        value:
          "pvc-fc9a0dca-5b5a-4680-afc1-9c532fb02bee"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value:
          "29Gi"
    target:
      group: apps
      kind: StatefulSet
      name: dependencytrack-api
      version: v1

  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccount
        value:
          "dependencytrack"
    target:
      group: apps
      kind: Deployment
      name: dependencytrack-frontend
      version: v1

configMapGenerator:
  - behavior: "replace"
    envs:
      - dependencytrack.env
    name: dependencytrack-config
  - behavior: "replace"
    envs:
      - dependencytrack-api.env
    name: dependencytrack-api-config

resources:
  - ../../base
  - sa.yaml
